name = "random"
version = "0.1.0"
standard = "c++17"
project_type = "bin"

[[owners]]
name = "cardinal"
email = "unset"

[[dependency]]
name = "opencv4"
version = "*"

[[dependency]]
name = "gtk+-3.0"
version = "*"
